name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master      
      - name: send photo message
        uses: appleboy/telegram-action@master
        with:
          to: 1382384821
          token: 6884130466:AAEuzWVdzhIgjimUO2r9y0QZeZEhzpqAQtY
          message: send photo message
          photo: ./a9d9562f-d6fa-4abd-99e7-317b6f614c82.jpg
